In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('DataSet.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['England' 24.0 1500000.0]
 ['France' 20.0 2000000.0]
 ['Greece' 25.0 1300000.0]
 ['Greece' 30.0 2500000.0]
 ['England' 23.0 nan]
 ['England' 26.0 2800000.0]
 ['France' 35.0 3000000.0]
 ['France' nan 1000000.0]
 ['England' 35.0 4000000.0]
 ['Greece' 36.0 nan]]


In [4]:
print(y)

['Rendah' 'Tinggi' 'Rendah' 'Tinggi' 'Rendah' 'Tinggi' 'Tinggi' 'Rendah'
 'Tinggi' 'Rendah']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 0:3])
x[:, 0:3] = imputer.transform(x[:, 0:3])

ValueError: Cannot use mean strategy with non-numeric data:
could not convert string to float: 'England'

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [7]:
print(x)

[['England' 24.0 1500000.0]
 ['France' 20.0 2000000.0]
 ['Greece' 25.0 1300000.0]
 ['Greece' 30.0 2500000.0]
 ['England' 23.0 2262500.0]
 ['England' 26.0 2800000.0]
 ['France' 35.0 3000000.0]
 ['France' 28.22222222222222 1000000.0]
 ['England' 35.0 4000000.0]
 ['Greece' 36.0 2262500.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 24.0 1500000.0]
 [0.0 1.0 0.0 20.0 2000000.0]
 [0.0 0.0 1.0 25.0 1300000.0]
 [0.0 0.0 1.0 30.0 2500000.0]
 [1.0 0.0 0.0 23.0 2262500.0]
 [1.0 0.0 0.0 26.0 2800000.0]
 [0.0 1.0 0.0 35.0 3000000.0]
 [0.0 1.0 0.0 28.22222222222222 1000000.0]
 [1.0 0.0 0.0 35.0 4000000.0]
 [0.0 0.0 1.0 36.0 2262500.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 1 0 1 0 1 1 0 1 0]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 1)

In [13]:
print(x_train)

[[0.0 1.0 0.0 35.0 3000000.0]
 [1.0 0.0 0.0 23.0 2262500.0]
 [1.0 0.0 0.0 24.0 1500000.0]
 [0.0 0.0 1.0 30.0 2500000.0]
 [0.0 1.0 0.0 20.0 2000000.0]
 [0.0 1.0 0.0 28.22222222222222 1000000.0]
 [1.0 0.0 0.0 35.0 4000000.0]
 [1.0 0.0 0.0 26.0 2800000.0]]


In [14]:
print(x_test)

[[0.0 0.0 1.0 25.0 1300000.0]
 [0.0 0.0 1.0 36.0 2262500.0]]


In [15]:
print(y_train)

[1 0 0 1 1 0 1 1]


In [16]:
print(y_test)

[0 0]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[0.0 1.0 0.0 1.4337412293228604 0.710506355359774]
 [1.0 0.0 0.0 -0.9079457690418873 -0.1385037705384876]
 [1.0 0.0 0.0 -0.712805185844825 -1.0162939007044869]
 [0.0 0.0 1.0 0.45803831333754885 0.1349062700050204]
 [0.0 1.0 0.0 -1.4933675186330742 -0.44069381534973323]
 [0.0 1.0 0.0 0.11112172098721572 -1.5918939860592405]
 [1.0 0.0 0.0 1.4337412293228604 1.8617065260692813]
 [1.0 0.0 0.0 -0.32252401945070036 0.48026632121787255]]


In [19]:
print(x_test)

[[0.0 0.0 1.0 -0.5176646026477626 -1.2465339348463884]
 [0.0 0.0 1.0 1.6288818125199227 -0.1385037705384876]]
